update

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -4,7 +4,7 @@ set -e
 
 echo "Building Jekyll site"
 
-echo "Run publication generator"
+echo "Prepare publication generator"
 
 # install dependencies
 cd ./script
@@ -13,9 +13,19 @@ source bin/activate
 pip install bibtexparser
 pip install pyyaml
 
+echo "Run publication generator"
+
 # generate publication
 python publication_generator.py
 cd ../
+
+# test publications.yml
+if test -e "./_data/publications.yml";then
+  echo "publications.yml smokes!"
+else
+  echo "Build publications.yml failed"
+  exit 1
+fi
 
 # lint
 bundle exec scss-lint --config=.scss-lint.yml
@@ -24,7 +34,7 @@ bundle exec jekyll build
 
 # build Long English version
 if test -e "./_site/LResume.html";then
-  echo "It smokes!"
+  echo "LResume smokes!"
 else
   echo "Build Long EN version failed"
   exit 1
@@ -32,7 +42,7 @@ fi
 
 # build Short English version
 if test -e "./_site/SResume.html";then
-  echo "It smokes!"
+  echo "SResume smokes!"
 else
   echo "Build Short EN version failed"
   exit 1
@@ -40,7 +50,7 @@ fi
 
 # build Default English version
 if test -e "./_site/index.html";then
-  echo "It smokes!"
+  echo "index smokes!"
 else
   echo "Build Default EN version failed"
   exit 1
@@ -48,7 +58,7 @@ fi
 
 # build Chinese version
 if test -e "./_site/resume_zh-CN.html";then
-  echo "It smokes!"
+  echo "resume_zh-CN smokes!"
 else
   echo "Build CN version failed"
   exit 1
@@ -57,9 +67,9 @@ fi
 # build with Gem
 rm -rf ./_site
 bundle exec jekyll build --config ./_config_gem.yml
-if test -e "./_site/resume.html";then
-  echo "It smokes!"
+if test -e "./_site/LResume.html";then
+  echo "LResume with gem smokes!"
 else
-  echo "Build EN version with Gem failed"
+  echo "Build Long EN version with Gem failed"
   exit 1
 fi
